### ISSUE TITLE
map.values - Issue

### ISSUE THREAD

**Issue by KonstantinaChe** [BenjaminPeter/admixfrog#12]
Hello!

I have tried to run the admixfrog analysis several times and each time I received the same error, so I decided to re-run it on the uploaded data in tests/data directory. The same issue persists. Here it is:

admixfrog 0.7.2
{'ll_tol': 0.01, 'max_iter': 1000, 'scale_probs': True}
Traceback (most recent call last):
  File "/lisc/app/admixfrog/0.7.2-3.12.5/bin/admixfrog", line 8, in <module>
    sys.exit(run_frog())
             ^^^^^^^^^^
  File "/lisc/app/admixfrog/0.7.2-3.12.5/admixfrog/interface_frog.py", line 335, in run_frog
    run_admixfrog(
  File "/lisc/app/admixfrog/0.7.2-3.12.5/admixfrog/frog/admixfrog.py", line 492, in run_admixfrog
    df, ix, sex, tot_n_snps = load_admixfrog_data(
                              ^^^^^^^^^^^^^^^^^^^^
  File "/lisc/app/admixfrog/0.7.2-3.12.5/admixfrog/frog/admixfrog.py", line 329, in load_admixfrog_data
    ref = load_ref(
          ^^^^^^^^^
  File "/lisc/app/admixfrog/0.7.2-3.12.5/admixfrog/utils/input.py", line 86, in load_ref
    ref0 = ref0[~np.isnan(ref0.reset_index("map").map.values)]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'values'

I would appreciate your help on the matter.

**Comment by BenjaminPeter** [comment]
Hi Konstantina. This bug was due to newer versions of pandas assigning `map` to something else. Version [0.7.3](https://github.com/BenjaminPeter/admixfrog/releases/tag/0.7.3) should have this fixed.

Ben #
