### ISSUE TITLE
admixfrog-bam NotImplementedError

### ISSUE THREAD

**Issue by ma-diroma** [BenjaminPeter/admixfrog#2]
Hi,

I would like to generate admixfrog input from my BAM file, after generating reference.xz file.

This is the command launched

`admixfrog-bam --bam sample_rmdup.sorted.bam --ref afr_nea_ref_samples.xz --random-read-sample --chroms 21 --deam-cutoff 3 --minmapq 30 --length-bin-size 35 --out sample.in.xz > admf_in.log 2> admf_in.err`

However the process exits after a few seconds with this error

```
...
[18:20:31]:  Filter is {'deam_only': False, 'pos_in_read_cutoff': 2, 'min_length': 35, 'max_length': 1000, 'minq': 25, 'minmapq': 30, 'report_alleles': False}
Traceback (most recent call last):
  File "/home/student6/anaconda3/envs/python38/bin/admixfrog-bam", line 8, in <module> 
    sys.exit(bam()) 
  File "/home/student6/anaconda3/envs/python38/lib/python3.8/site-packages/admixfrog/interface.py", line 141, in bam
    process_bam(**args)
  File "/home/student6/anaconda3/envs/python38/lib/python3.8/site-packages/admixfrog/bam.py", line 200, in process_bam
    cov = AdmixfrogInput( 
  File "/home/student6/anaconda3/envs/python38/lib/python3.8/site-packages/admixfrog/bam.py", line 27, in __init__
    raise NotImplementedError
NotImplementedError
```

Could you please help me?

Best wishes,
Maria Angela

**Comment by ma-diroma** [comment]
Hi,

I have solved just by removing `--random-read-sample` option.

I have another doubt. I am building the reference file from vcf with `admixfrog-ref` and I would like to add ancestral info, which is present in my vcf file. However, I see no difference between reference.xz files generated with or without `--ancestral` option. The header of both files contains these fields
`
chrom,pos,ref,alt,map,AA_Map,AFR_ref,AFR_alt,NEA_ref,NEA_alt`

while I expected to find also ANC_ref and ANC_alt, and I cannot see clear differences in their content.
Could you please help me to understand how ancestral information are retrieved and then used by the admixfrog main command?

This is  the command line I used

`admixfrog-ref --outfile ref.xz --pop-file ref_samples.yaml --states AFR NEA --ancestral ANC --vcf-ref myref.vcf.gz --rec-file maps_chr.{CHROM} --map-id AA_Map`

For the `ref_samples.yaml` I followed your instructions (both adding/not adding one line specifying it is pseudohaploid).
I also tested using 2 different versions of my input vcf file, with ancestral sample diploid or haploid genotype, but no changes in output also in these cases.

Please find attached log and err files from `admixfrog-ref` processes using a vcf containing ancestral diploid genotype (together with Neanderthal and African samples):
ref1: ANC added in the ref_samples.yaml file, also specified pseudohaploidy
ref2: ANC added in the ref_samples.yaml file, no pseudohaploidy line
ref_noANC: no ancestral sample

[ref1.err.txt](https://github.com/BenjaminPeter/admixfrog/files/6358062/ref1.err.txt)
[ref2.err.txt](https://github.com/BenjaminPeter/admixfrog/files/6358140/ref2.err.txt)
[ref_noANC.log.txt](https://github.com/BenjaminPeter/admixfrog/files/6358486/ref_noANC.log.txt)
[ref1.log.txt](https://github.com/BenjaminPeter/admixfrog/files/6358488/ref1.log.txt)
[ref2.log.txt](https://github.com/BenjaminPeter/admixfrog/files/6358489/ref2.log.txt)
[ref_noANC.err.txt](https://github.com/BenjaminPeter/admixfrog/files/6358490/ref_noANC.err.txt)

Thanks,
Maria Angela
